export const state = {
  gameState: "MENU",
  frameCount: 0,
  scoreTime: 0,
  currentLevel: 1,
  maxFramesToSurvive: 0,
  isBossLevel: false,

  player: null,
  boss: null,
  bullets: [],
  ghosts: [],
  // ===== Painter =====
  painterTrails: [],
  painterZones: [],
  painterDrawing: false,
  painterDrawTime: 0,
  pastRuns: [],
  currentRunRecord: [],
  ownedCharacters: ["speedster"],
  selectedCharacter: "speedster",
  resources: {
    common: 0,
    rare: 0,
    legendary: 0,
  },
  bossFragments: [],
  characterUpgrades: {
    spd: { count: 0, specialEffect: false },
    fire: { count: 0, specialEffect: false },
    multi: { count: 0, specialEffect: false },
    bounce: { count: 0, specialEffect: false },
    dash: { count: 0, specialEffect: false },
  },

  keys: {},
  prevKeys: {},
  mouse: { x: 0, y: 0, clicked: false },
  loopId: null,

  // Hàng đợi các tác vụ trì hoãn (thay thế cho setTimeout)
  delayedTasks: [],

  skillsCD: { q: 0, e: 0, r: 0 },
  activeBuffs: { q: 0, e: 0, r: 0 },

  // Biến kĩ năng cho từng nhân vật (để reset sạch sẽ khi đổi màn)
  phoenixTrails: [],
  phoenixEfx: null,
  phoenixReviveReady: false,
  necroMinions: [],
  necroZone: null,
  necroExplosions: [],
  voidBlackholes: [],
  voidLaser: null,
  stormTraps: [],
  stormLightnings: [],
  explosions: [],
  druidOrbs: [],
  phantoms: [],
  painterTrails: [],
  painterZones: [],
  painterBomb: null,
  painterExplosions: [],
  hunterTraps: [],
  engineerTurrets: [],
  gunnerMines: [],
  gunnerAirstrikes: [],
  gunnerLaser: null,
  reaperSlash: null,
  destroyerRifts: [],
  destroyerUlt: null,
  creatorTurrets: [],
  creatorHolyZone: null,
  creatorOrbs: [],
  creatorDeathSave: false,
  knightCharge: null,
  knightShield: null,
  knightRage: null,
  isScoutQ: false,

  phaseTransitionTimer: 0,
  currentPhaseName: "",
  lastBossPhase: -1,

  rerollCount: 0,

  upgrades: {
    spd: 0,
    fire: 0,
    multi: 0,
    bounce: 0,
    dash: 0,
    regen: 0,
    hp_up: 0,
    shield_up: 0,
  },

  evolutions: {
    spd: false,
    fire: false,
    multi: false,
    bounce: false,
    dash: false,
    regen: false,
    hp_up: false,
    shield_up: false,
  },

  evolutionReady: null,
};
